global using System.ComponentModel;
global using Ardalis.Specification;
global using FluentValidation;
global using Mapster;
global using MultiMart.Domain.Common;
global using MediatR;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using MultiMart.Application.Common.Persistence;